extension_dir=ext
extension=openssl
extension=curl
extension=fileinfo
extension=mbstring
extension=pdo_mysql
extension=pdo_sqlite
extension=mysqli
extension=sqlite3
extension=zip

memory_limit=512M
max_execution_time=120
date.timezone=Africa/Cairo
variables_order=GPCS
